services:
  - type: web
    name: data-exhaust-frontend
    runtime: node
    rootDir: frontend
    buildCommand: npm install && npm run build && cp -r .next/static .next/standalone/.next/static && cp -r public .next/standalone/public
    startCommand: node .next/standalone/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOSTNAME
        value: 0.0.0.0
      - key: NEXT_PUBLIC_API_URL
        value: https://one2-2-l5hl.onrender.com

  - type: web
    name: data-exhaust-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://data-exhaust-frontend.onrender.com,http://localhost:3000,http://127.0.0.1:3000
